pygments: true
auto: true

# Set the title, tagline of the site
title: Nicaragua.OpenSpending.org
tagline: Where does Nicaragua's Money Go?

# Where is the template located (if it's not in the root)
# Remove the '#' from the next line and update the path if you have
# a subdirectory
# subdirectory: '/mysatellitesite'

# Set your Google Analytics Tracking Code
#ga_tracking_code: UA-8271754-8

# Where do you want to load openspendingjs from
openspendingjs: 'https://openspending.org/static/openspendingjs'

# Frontpage configurations
# We recommend you leave the openspending clause as is (or close to
# it as you can, e.g. you can replace "on this site" with
# "on [your site title]" or translate it.
frontpage:
    title: Here you can analyse the Nicaraguan budget for 2014
    openspending: |-
        The data presented on this site comes from
        <a href="https://openspending.org">OpenSpending</a>, 
        where you can find information about 
        government finance from countries across the world.

# Bubblemap configuration include bubbletree and map
# If you don't want bubblemap set this to false
# bubblemap : false
# If you don't include map configurations, only the BubbleTree will be shown
# This shows by default the UK country/regional analysis finances
bubblemap:
    title: Nicaraguan bubbletree
    description: |-
        How much is spent on the various functions of 
        government in total &mdash; and where?
    tree:
        dataset: presupfinal
        cuts:
            - year:2014
        drilldowns:
            - cofog1
            - cofog2
            - cofog3
        rootlabel: Total
